### PR TITLE
Feature/us 0000052

### PR DESCRIPTION
**Pull request by microweii**
Hi @swongcopado , the extra commits issue is happening again.
In Copado, I created this US 52 with only these selections:
image
It also only records one commit:
image
But you can see in PR that it's somehow getting the commits from US 51 feature branch. Also note that US 51 has already been promoted all the way through to Prod.

I _think_ it's something to do with user stories being setup by default to branch from main, but not sure specifically...

How do we avoid this?

### CODE REVIEW

**Comment by swongcopado** [comment]
I do not think that the feature branch being created from the main branch should be the cause of this issue.. but it is indeed weird. 

If I manually in git try to create a PR to merge from feature/US-0000052 to test1, it shows 11 files... not 13 like this one.

Let me bounce this off with my other colleagues to see if they've seen this. It is weird and I agree it shouldn't be like this.

**Comment by microweii** [comment]
That's interesting, looks like the other commits were automatically integrated into the test1 branch sometime after this PR was made. 

Maybe there's a lag period between a promotion deployment branch & its integration with the corresponding org branch. Would like to know what that is if that's the case.

**Comment by swongcopado** [comment]
Yeah, I was trying a few things last night and could reproduce the issue. Then I did a new test this morning and that issue is not there. I am having the same thoughts but will have to confirm.
That said, a colleague shared this article with me about this - 

https://docs.copado.com/articles/#!copado-ci-cd-publication/pull-request-shows-changes-unrelated-to-the-components-committed-on-the-user-story/q/Pull%2520request/qid/37123/qp/6

It details the scenarios this could happen but I am still testing this out :-)

**Comment by swongcopado** [comment]
tested this out and as the documentation suggests, 2 scenarios for this to happen. 
deployment to main from a user story from hotfix or
deployment to main where there was a conflict resolution.
basically the commits to main are retained when the branch was created from main (as you suggested earlier)
it is a git behavior as I tried to do the same outside of Copado (i.e. create a branch of main, add some files, commit, then create a PR to merge the branch to sit and I can see the same commits). 
Its something to do with how git calculates the commits ahead or whatnot... something too complicated for my small brains :-D

**Pull request closed without merging**
