### PR TITLE
Feature/us 0000040

### PR DESCRIPTION
**Pull request by microweii**
Landed here from Copado "Open PR" button in user story and after logging into this GitHub account.

If the repo host (swongcopado) sees this: I'd like to understand how PRs should be handled. For example:

- If we merge the PR within GitHub, does Copado automatically handle the necessary updates on SFDC (User story, promotion, deployment records, etc.)?
- If we just use PRs to record approvals and do nothing, then perform the promotion/deploy in Copado UI, does the PR track those updates?
- What would you suggest as protocol for PR handling with Copado?

### CODE REVIEW

**Review by microweii — COMMENTED** [review]
DR_FullRollbackTest DRs were not included in the original story commit, so unsure why they are here.

I cannot self-approve my own PR (good).

**Comment by swongcopado** [comment]
Hi Michael,

Essentially you only use this feature to comment/approve the PR. 
You do not need to merge the PR and most importantly DO NOT DELETE the source branch. 

All comments/approvals/close of this PR will be logged back in Copado under the Pull Request object.

**Comment by swongcopado** [comment]
The ability to set yourself as approver/reviewer is limited by the git repo. In the case of Github, it is possible to approve your own changes.

**Review by swongcopado — APPROVED** [review]
This is approved.

**Comment by microweii** [comment]
Thanks for the feedback @swongcopado , that's very helpful.
Could you help explain what I see as some sort of bug:

- In Copado I created US-0000040, assign to Dev1 credentials and from that UI, committed just the DR_TestPR dataraptor item.
- Then I clicked "Open Pull Request" as described above
- In the "Files changed" tab of this PR, I also somehow see 2 other DRs, named DR_FullRollbackTest
-     These 2 DRs were originally created in TEST org, so in no way visible to US-0000040 from UI

Is the above behaviour intended? I'd be confused as a reviewer if I saw changes from both source and target orgs/branches in the same PR like that.

**Pull request closed without merging**
